# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'P:\nastran\myNastran\vtk_fem\gui\picking_toolbar\picking_toolbar_ui.ui'
#
# Created: Wed Dec 23 08:43:10 2015
#      by: PyQt4 UI code generator 4.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName(_fromUtf8("Form"))
        Form.resize(785, 43)
        self.gridLayout = QtGui.QGridLayout(Form)
        self.gridLayout.setMargin(0)
        self.gridLayout.setSpacing(0)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.visible_only = QtGui.QPushButton(Form)
        self.visible_only.setMinimumSize(QtCore.QSize(41, 41))
        self.visible_only.setMaximumSize(QtCore.QSize(41, 41))
        font = QtGui.QFont()
        font.setPointSize(6)
        self.visible_only.setFont(font)
        self.visible_only.setAutoDefault(False)
        self.visible_only.setDefault(False)
        self.visible_only.setFlat(False)
        self.visible_only.setObjectName(_fromUtf8("visible_only"))
        self.horizontalLayout.addWidget(self.visible_only)
        self.box_picking = QtGui.QPushButton(Form)
        self.box_picking.setMinimumSize(QtCore.QSize(41, 41))
        self.box_picking.setMaximumSize(QtCore.QSize(41, 41))
        font = QtGui.QFont()
        font.setPointSize(6)
        self.box_picking.setFont(font)
        self.box_picking.setAutoDefault(False)
        self.box_picking.setDefault(False)
        self.box_picking.setFlat(False)
        self.box_picking.setObjectName(_fromUtf8("box_picking"))
        self.horizontalLayout.addWidget(self.box_picking)
        self.poly_picking = QtGui.QPushButton(Form)
        self.poly_picking.setMinimumSize(QtCore.QSize(41, 41))
        self.poly_picking.setMaximumSize(QtCore.QSize(41, 41))
        font = QtGui.QFont()
        font.setPointSize(6)
        self.poly_picking.setFont(font)
        self.poly_picking.setAutoDefault(False)
        self.poly_picking.setDefault(False)
        self.poly_picking.setFlat(False)
        self.poly_picking.setObjectName(_fromUtf8("poly_picking"))
        self.horizontalLayout.addWidget(self.poly_picking)
        self.gridLayout.addLayout(self.horizontalLayout, 0, 0, 1, 1)
        spacerItem = QtGui.QSpacerItem(0, 38, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem, 0, 1, 1, 1)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setSpacing(0)
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.append_selection = QtGui.QPushButton(Form)
        self.append_selection.setMinimumSize(QtCore.QSize(41, 41))
        self.append_selection.setMaximumSize(QtCore.QSize(41, 41))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.append_selection.setFont(font)
        self.append_selection.setAutoDefault(False)
        self.append_selection.setDefault(False)
        self.append_selection.setFlat(False)
        self.append_selection.setObjectName(_fromUtf8("append_selection"))
        self.horizontalLayout_2.addWidget(self.append_selection)
        self.subtract_selection = QtGui.QPushButton(Form)
        self.subtract_selection.setMinimumSize(QtCore.QSize(41, 41))
        self.subtract_selection.setMaximumSize(QtCore.QSize(41, 41))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.subtract_selection.setFont(font)
        self.subtract_selection.setAutoDefault(False)
        self.subtract_selection.setDefault(False)
        self.subtract_selection.setFlat(False)
        self.subtract_selection.setObjectName(_fromUtf8("subtract_selection"))
        self.horizontalLayout_2.addWidget(self.subtract_selection)
        self.set_selection = QtGui.QPushButton(Form)
        self.set_selection.setMinimumSize(QtCore.QSize(41, 41))
        self.set_selection.setMaximumSize(QtCore.QSize(41, 41))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.set_selection.setFont(font)
        self.set_selection.setAutoDefault(False)
        self.set_selection.setDefault(False)
        self.set_selection.setFlat(False)
        self.set_selection.setObjectName(_fromUtf8("set_selection"))
        self.horizontalLayout_2.addWidget(self.set_selection)
        self.gridLayout.addLayout(self.horizontalLayout_2, 0, 2, 1, 1)
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem1, 0, 3, 1, 1)
        self.select_node = QtGui.QPushButton(Form)
        self.select_node.setMinimumSize(QtCore.QSize(41, 41))
        self.select_node.setMaximumSize(QtCore.QSize(41, 41))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.select_node.setFont(font)
        self.select_node.setAutoDefault(False)
        self.select_node.setDefault(False)
        self.select_node.setFlat(False)
        self.select_node.setObjectName(_fromUtf8("select_node"))
        self.gridLayout.addWidget(self.select_node, 0, 4, 1, 1)
        spacerItem2 = QtGui.QSpacerItem(0, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem2, 0, 5, 1, 1)
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setSpacing(0)
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.select_all = QtGui.QPushButton(Form)
        self.select_all.setMinimumSize(QtCore.QSize(41, 41))
        self.select_all.setMaximumSize(QtCore.QSize(41, 41))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.select_all.setFont(font)
        self.select_all.setAutoDefault(False)
        self.select_all.setDefault(False)
        self.select_all.setFlat(False)
        self.select_all.setObjectName(_fromUtf8("select_all_elements"))
        self.horizontalLayout_3.addWidget(self.select_all)
        self.select_point = QtGui.QPushButton(Form)
        self.select_point.setMinimumSize(QtCore.QSize(41, 41))
        self.select_point.setMaximumSize(QtCore.QSize(41, 41))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.select_point.setFont(font)
        self.select_point.setAutoDefault(False)
        self.select_point.setDefault(False)
        self.select_point.setFlat(False)
        self.select_point.setObjectName(_fromUtf8("select_point"))
        self.horizontalLayout_3.addWidget(self.select_point)
        self.select_line = QtGui.QPushButton(Form)
        self.select_line.setMinimumSize(QtCore.QSize(41, 41))
        self.select_line.setMaximumSize(QtCore.QSize(41, 41))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.select_line.setFont(font)
        self.select_line.setAutoDefault(False)
        self.select_line.setDefault(False)
        self.select_line.setFlat(False)
        self.select_line.setObjectName(_fromUtf8("select_line"))
        self.horizontalLayout_3.addWidget(self.select_line)
        self.select_tri = QtGui.QPushButton(Form)
        self.select_tri.setMinimumSize(QtCore.QSize(41, 41))
        self.select_tri.setMaximumSize(QtCore.QSize(41, 41))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.select_tri.setFont(font)
        self.select_tri.setAutoDefault(False)
        self.select_tri.setDefault(False)
        self.select_tri.setFlat(False)
        self.select_tri.setObjectName(_fromUtf8("select_tri"))
        self.horizontalLayout_3.addWidget(self.select_tri)
        self.select_quad = QtGui.QPushButton(Form)
        self.select_quad.setMinimumSize(QtCore.QSize(41, 41))
        self.select_quad.setMaximumSize(QtCore.QSize(41, 41))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.select_quad.setFont(font)
        self.select_quad.setAutoDefault(False)
        self.select_quad.setDefault(False)
        self.select_quad.setFlat(False)
        self.select_quad.setObjectName(_fromUtf8("select_quad"))
        self.horizontalLayout_3.addWidget(self.select_quad)
        self.select_shell = QtGui.QPushButton(Form)
        self.select_shell.setMinimumSize(QtCore.QSize(41, 41))
        self.select_shell.setMaximumSize(QtCore.QSize(41, 41))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.select_shell.setFont(font)
        self.select_shell.setAutoDefault(False)
        self.select_shell.setDefault(False)
        self.select_shell.setFlat(False)
        self.select_shell.setObjectName(_fromUtf8("select_shell"))
        self.horizontalLayout_3.addWidget(self.select_shell)
        self.select_tet = QtGui.QPushButton(Form)
        self.select_tet.setMinimumSize(QtCore.QSize(41, 41))
        self.select_tet.setMaximumSize(QtCore.QSize(41, 41))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.select_tet.setFont(font)
        self.select_tet.setAutoDefault(False)
        self.select_tet.setDefault(False)
        self.select_tet.setFlat(False)
        self.select_tet.setObjectName(_fromUtf8("select_tet"))
        self.horizontalLayout_3.addWidget(self.select_tet)
        self.select_wedge = QtGui.QPushButton(Form)
        self.select_wedge.setMinimumSize(QtCore.QSize(41, 41))
        self.select_wedge.setMaximumSize(QtCore.QSize(41, 41))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.select_wedge.setFont(font)
        self.select_wedge.setAutoDefault(False)
        self.select_wedge.setDefault(False)
        self.select_wedge.setFlat(False)
        self.select_wedge.setObjectName(_fromUtf8("select_wedge"))
        self.horizontalLayout_3.addWidget(self.select_wedge)
        self.select_solid = QtGui.QPushButton(Form)
        self.select_solid.setMinimumSize(QtCore.QSize(41, 41))
        self.select_solid.setMaximumSize(QtCore.QSize(41, 41))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.select_solid.setFont(font)
        self.select_solid.setAutoDefault(False)
        self.select_solid.setDefault(False)
        self.select_solid.setFlat(False)
        self.select_solid.setObjectName(_fromUtf8("select_solid"))
        self.horizontalLayout_3.addWidget(self.select_solid)
        self.select_free_edge = QtGui.QPushButton(Form)
        self.select_free_edge.setMinimumSize(QtCore.QSize(41, 41))
        self.select_free_edge.setMaximumSize(QtCore.QSize(41, 41))
        font = QtGui.QFont()
        font.setPointSize(6)
        self.select_free_edge.setFont(font)
        self.select_free_edge.setAutoDefault(False)
        self.select_free_edge.setDefault(False)
        self.select_free_edge.setFlat(False)
        self.select_free_edge.setObjectName(_fromUtf8("select_free_edge"))
        self.horizontalLayout_3.addWidget(self.select_free_edge)
        self.select_free_face = QtGui.QPushButton(Form)
        self.select_free_face.setMinimumSize(QtCore.QSize(41, 41))
        self.select_free_face.setMaximumSize(QtCore.QSize(41, 41))
        font = QtGui.QFont()
        font.setPointSize(6)
        self.select_free_face.setFont(font)
        self.select_free_face.setAutoDefault(False)
        self.select_free_face.setDefault(False)
        self.select_free_face.setFlat(False)
        self.select_free_face.setObjectName(_fromUtf8("select_free_face"))
        self.horizontalLayout_3.addWidget(self.select_free_face)
        self.gridLayout.addLayout(self.horizontalLayout_3, 0, 6, 1, 1)
        spacerItem3 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem3, 0, 7, 1, 1)
        self.select_mpc = QtGui.QPushButton(Form)
        self.select_mpc.setMinimumSize(QtCore.QSize(41, 41))
        self.select_mpc.setMaximumSize(QtCore.QSize(41, 41))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.select_mpc.setFont(font)
        self.select_mpc.setAutoDefault(False)
        self.select_mpc.setDefault(False)
        self.select_mpc.setFlat(False)
        self.select_mpc.setObjectName(_fromUtf8("select_mpc"))
        self.gridLayout.addWidget(self.select_mpc, 0, 8, 1, 1)
        spacerItem4 = QtGui.QSpacerItem(0, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem4, 0, 9, 1, 1)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        Form.setWindowTitle(_translate("Form", "Form", None))
        self.visible_only.setText(_translate("Form", "Visible Only", None))
        self.box_picking.setText(_translate("Form", "box", None))
        self.poly_picking.setText(_translate("Form", "poly", None))
        self.append_selection.setText(_translate("Form", "+", None))
        self.subtract_selection.setText(_translate("Form", "-", None))
        self.set_selection.setText(_translate("Form", "=", None))
        self.select_node.setText(_translate("Form", "Node", None))
        self.select_all.setText(_translate("Form", "All", None))
        self.select_point.setText(_translate("Form", "Point", None))
        self.select_line.setText(_translate("Form", "Line", None))
        self.select_tri.setText(_translate("Form", "Tri", None))
        self.select_quad.setText(_translate("Form", "Quad", None))
        self.select_shell.setText(_translate("Form", "Shell", None))
        self.select_tet.setText(_translate("Form", "Tet", None))
        self.select_wedge.setText(_translate("Form", "Wedge", None))
        self.select_solid.setText(_translate("Form", "Solid", None))
        self.select_free_edge.setText(_translate("Form", "w/Free Edges", None))
        self.select_free_face.setText(_translate("Form", "w/Free Faces", None))
        self.select_mpc.setText(_translate("Form", "MPC", None))


if __name__ == "__main__":
    import sys
    app = QtGui.QApplication(sys.argv)
    Form = QtGui.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())

