# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'P:\redmond\mrFleet\gui\vtk_widget\plotting_toolbar\_plotting_ui.ui'
#
# Created by: PyQt5 UI code generator 5.6
#
# WARNING! All changes made in this file will be lost!

from qtpy import QtCore, QtGui, QtWidgets

class Ui_DockWidget(object):
    def setupUi(self, DockWidget):
        DockWidget.setObjectName("DockWidget")
        DockWidget.resize(478, 648)
        self.dockWidgetContents = QtWidgets.QWidget()
        self.dockWidgetContents.setObjectName("dockWidgetContents")
        self.gridLayout = QtWidgets.QGridLayout(self.dockWidgetContents)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.plainTextEdit = QtWidgets.QPlainTextEdit(self.dockWidgetContents)
        self.plainTextEdit.setObjectName("plainTextEdit")
        self.gridLayout.addWidget(self.plainTextEdit, 0, 0, 1, 6)
        self.plot_button = QtWidgets.QPushButton(self.dockWidgetContents)
        self.plot_button.setObjectName("plot_button")
        self.gridLayout.addWidget(self.plot_button, 1, 0, 1, 1)
        self.erase_button = QtWidgets.QPushButton(self.dockWidgetContents)
        self.erase_button.setObjectName("erase_button")
        self.gridLayout.addWidget(self.erase_button, 1, 1, 1, 1)
        self.clear_button = QtWidgets.QPushButton(self.dockWidgetContents)
        self.clear_button.setObjectName("clear_button")
        self.gridLayout.addWidget(self.clear_button, 1, 2, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(26, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem, 1, 3, 1, 1)
        self.listWidget = QtWidgets.QListWidget(self.dockWidgetContents)
        self.listWidget.setObjectName("listWidget")
        item = QtWidgets.QListWidgetItem()
        item.setCheckState(QtCore.Qt.Checked)
        self.listWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        item.setCheckState(QtCore.Qt.Checked)
        self.listWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        item.setCheckState(QtCore.Qt.Checked)
        self.listWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        item.setCheckState(QtCore.Qt.Checked)
        self.listWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        item.setCheckState(QtCore.Qt.Checked)
        self.listWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        item.setCheckState(QtCore.Qt.Checked)
        self.listWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        item.setCheckState(QtCore.Qt.Checked)
        self.listWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        item.setCheckState(QtCore.Qt.Checked)
        self.listWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        item.setCheckState(QtCore.Qt.Checked)
        self.listWidget.addItem(item)
        self.gridLayout.addWidget(self.listWidget, 2, 0, 1, 2)
        spacerItem1 = QtWidgets.QSpacerItem(72, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem1, 2, 2, 1, 1)
        spacerItem2 = QtWidgets.QSpacerItem(26, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem2, 3, 4, 1, 1)
        self.done_button = QtWidgets.QPushButton(self.dockWidgetContents)
        self.done_button.setObjectName("done_button")
        self.gridLayout.addWidget(self.done_button, 3, 5, 1, 1)
        DockWidget.setWidget(self.dockWidgetContents)

        self.retranslateUi(DockWidget)
        QtCore.QMetaObject.connectSlotsByName(DockWidget)

    def retranslateUi(self, DockWidget):
        _translate = QtCore.QCoreApplication.translate
        DockWidget.setWindowTitle(_translate("DockWidget", "DockWidget"))
        self.plot_button.setText(_translate("DockWidget", "Plot"))
        self.erase_button.setText(_translate("DockWidget", "Erase"))
        self.clear_button.setText(_translate("DockWidget", "Clear"))
        __sortingEnabled = self.listWidget.isSortingEnabled()
        self.listWidget.setSortingEnabled(False)
        item = self.listWidget.item(0)
        item.setText(_translate("DockWidget", "All"))
        item = self.listWidget.item(1)
        item.setText(_translate("DockWidget", "FEM"))
        item = self.listWidget.item(2)
        item.setText(_translate("DockWidget", "Grid"))
        item = self.listWidget.item(3)
        item.setText(_translate("DockWidget", "Point Elements"))
        item = self.listWidget.item(4)
        item.setText(_translate("DockWidget", "Line Elements"))
        item = self.listWidget.item(5)
        item.setText(_translate("DockWidget", "Tri Elements"))
        item = self.listWidget.item(6)
        item.setText(_translate("DockWidget", "Quad Elements"))
        item = self.listWidget.item(7)
        item.setText(_translate("DockWidget", "Shell Elements"))
        item = self.listWidget.item(8)
        item.setText(_translate("DockWidget", "MPC\'s"))
        self.listWidget.setSortingEnabled(__sortingEnabled)
        self.done_button.setText(_translate("DockWidget", "Done"))

